### ISSUE TITLE
Velux Display issues with IE

### ISSUE THREAD

**Issue by fjarrett** [godaddy-wordpress/primer-child-velux#37]
_From @bridgessudbury on January 27, 2017 19:20_

The Velux theme does not display correctly when using internet explorer. 

Loads with main image blown up huge and menus/buttons do not display or show incorrectly.
Picture items (products, etc) show up distorted
Theme placed footer items etc do not load in correctly

_Copied from original issue: godaddy/wp-primer-theme#149_

**Comment by fjarrett** [comment]
_From @EvanHerman on January 27, 2017 19:26_

Hi @bridgessudbury,

What version of Internet Explorer are you testing with?


Evan

**Comment by fjarrett** [comment]
_From @bridgessudbury on January 27, 2017 21:26_

We are running Internet Explorer 11. 
The issue was brought to our attention by a customer, no way to know what version he was running. Verified with a friend running 11 as well. Tried clearing cache etc.

url is [https://www.bridgessudbury.ca](url)

**Comment by fjarrett** [comment]
_From @bridgessudbury on January 27, 2017 21:29_

Also checked with Edge and it loads fine. Same as chrome etc, seems to just be IE....

**Comment by fjarrett** [comment]
_From @EvanHerman on January 31, 2017 22:45_

Hi @bridgessudbury,

I am seeing it now when I test with [browserstack](http://www.browserstack.com). It looks like the image isn't being properly contained within it's container.

I will take a look into this and see what's going on, and see if I can replicate it on my end.

I'll report back here with some findings when I've had a chance to test.


Thanks,
Evan

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
