### ISSUE TITLE
Hero Text Disappearing After Adding Video to Header

### ISSUE THREAD

**Issue by 6thguards** [godaddy-wordpress/primer-child-velux#71]
Title says it all. Whenever I add a video to the header media, whether it is uploaded or via a YouTube link, the hero text disappears. It seems to be hidden by the video.

Photos do not affect it at all.

![image](https://user-images.githubusercontent.com/48769660/54709057-0e85ff00-4b45-11e9-8162-be36c448265a.png)

![image](https://user-images.githubusercontent.com/48769660/54709118-38d7bc80-4b45-11e9-9cbc-d449345913fb.png)

Not sure how to reorder it but would appreciate some assistance!

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
